version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: mapmosaic_db
    restart: always
    environment:
      POSTGRES_USER: group6
      POSTGRES_PASSWORD: MapMosaic
      POSTGRES_DB: map_mosaic
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: mapmosaic_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]

volumes:
  pgdata:
